name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone identify and fix the bug
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      placeholder: I get an error when I try to do X
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "Low"
        - "Medium"
        - "High"
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We will get back to you as soon as possible.
